//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.WinService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Contracts = new HashSet<Contract>();
            this.Quotes = new HashSet<Quote>();
            this.SourceQuotes = new HashSet<SourceQuote>();
        }
    
        public int ID { get; set; }
        public int roomID { get; set; }
        public int deviceTypeID { get; set; }
        public System.Guid submodalityID { get; set; }
        public string SerialNo { get; set; }
        public System.DateTime CommissionedDate { get; set; }
        public Nullable<System.Guid> commissioningCertID { get; set; }
        public Nullable<System.DateTime> FactoryShipmentFrom { get; set; }
        public Nullable<System.DateTime> FactoryShipmentTo { get; set; }
        public int ProductLineID { get; set; }
        public bool Deleted { get; set; }
        public string SalesLicenceNumber { get; set; }
        public string ModelNumber { get; set; }
        public string RadiationBoardSerialNumber { get; set; }
        public string SalesLicenceFileReferenceNumber { get; set; }
        public string EquipmentIDNumber { get; set; }
        public bool RequiresIBQCTests { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ProductLine ProductLine { get; set; }
        public virtual Room Room { get; set; }
        public virtual SubModality SubModality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceQuote> SourceQuotes { get; set; }
    }
}
