//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.WinService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteCalculationItem
    {
        public int ID { get; set; }
        public int QuoteCalculationID { get; set; }
        public short YearNo { get; set; }
        public decimal ROEPortionAmount { get; set; }
        public decimal ZARPortionAmount { get; set; }
        public decimal ROE { get; set; }
        public decimal IncrPerc { get; set; }
        public decimal AmountExclVAT { get; set; }
        public decimal AmountInclVAT { get; set; }
    
        public virtual QuoteCalculation QuoteCalculation { get; set; }
    }
}
