//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractItem
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public short ContractTypeID { get; set; }
        public byte ContractTerm { get; set; }
        public decimal BasePrice { get; set; }
        public decimal ROEPortion { get; set; }
        public decimal ZARPortion { get; set; }
        public decimal ROEPortionAmount { get; set; }
        public decimal ZARPortionAmount { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ContractTerm ContractTerm1 { get; set; }
        public virtual ContractType ContractType { get; set; }
    }
}
