//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public bool Deleted { get; set; }
        public int DeviceID { get; set; }
        public short ContractTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Device Device { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
