//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string ISOCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string CurrencyID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
