//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Customer1 = new HashSet<Customer>();
            this.Sites = new HashSet<Site>();
        }
    
        public int ID { get; set; }
        public string CustomerRef { get; set; }
        public string AccountRef { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNameFriendly { get; set; }
        public int customerTypeID { get; set; }
        public bool Deleted { get; set; }
        public string RegistrationNo { get; set; }
        public string PractiscId { get; set; }
        public string VATNo { get; set; }
        public int customerLocalityID { get; set; }
        public bool IsInternational { get; set; }
        public bool IsGovernment { get; set; }
        public Nullable<int> managementCompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        public virtual CustomerLocality CustomerLocality { get; set; }
        public virtual CustomerLocality CustomerLocality1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site> Sites { get; set; }
    }
}
