//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceComponent
    {
        public int ID { get; set; }
        public int deviceID { get; set; }
        public int componentTypeID { get; set; }
        public int brandModelID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual BrandModel BrandModel { get; set; }
    }
}
