//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWS.Domain.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.Contracts = new HashSet<Contract>();
            this.QuoteCalculations = new HashSet<QuoteCalculation>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CustomerID { get; set; }
        public int DeviceID { get; set; }
        public string TenderNo { get; set; }
        public string QuoteRef { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal ROE { get; set; }
        public System.DateTime ROEDate { get; set; }
        public float VAT { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Device Device { get; set; }
        public virtual SourceQuote SourceQuote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteCalculation> QuoteCalculations { get; set; }
    }
}
