//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.WinService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentMetaValues = new HashSet<DocumentMetaValue>();
            this.DocumentVersions = new HashSet<DocumentVersion>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid ID { get; set; }
        public string documentTypeID { get; set; }
        public string DocumentName { get; set; }
        public string RefNo { get; set; }
        public string TargetRef { get; set; }
        public int LatestVersionNumber { get; set; }
        public string LatestFileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LatestVersionDate { get; set; }
        public string LatestVersionCreator { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public long LatestSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentMetaValue> DocumentMetaValues { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentVersion> DocumentVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
