//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.WinService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetaValue
    {
        public int documentMetaFieldID { get; set; }
        public System.Guid documentID { get; set; }
        public string MetaValue { get; set; }
    
        public virtual DocumentMetaField DocumentMetaField { get; set; }
        public virtual Document Document { get; set; }
    }
}
