//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.WinService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVersionExpiry
    {
        public System.Guid documentId { get; set; }
        public int VersionNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string ModifyingUser { get; set; }
    
        public virtual DocumentVersion DocumentVersion { get; set; }
    }
}
